layout_spectrum: 0.3735891
typography_spectrum: 0.976386
color:
  saturation: 0.0653072
  lightness: 0.974131
  brandStrength: 0.6782816
  rhythmicContrast: 0.2894489
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Youth Camp 2016
