name: Youth Camp 2016
favicon: null
layout_spectrum: 0.3735891
typography_spectrum: 0.976386
title: Youth Camp 2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6782816
  lightness: 0.974131
  saturation: 0.0653072
  rhythmicContrast: 0.2894489
purpose: []
